[project]
name = "ragpoemgenerator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "faiss-cpu>=1.14.3",
    "gradio>=6.20.0",
    "numpy>=2.5.1",
    "ollama>=0.6.2",
    "sentence-transformers>=5.6.1",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
]
